# Length = [Å]        = 1e-10      [m]
# Mass   = [amu]      = 1.6605e-27 [kg]
# Energy = [kcal/mol] = 6.9478e-21 [J]
# Charge = [e]        = 1.6021e-19 [C]

[mass]
H =  1.0080
P = 30.9738
O = 15.9994
C = 12.0107
N = 14.0067

ALA =  71.09
ARG = 156.19
ASN = 114.11
ASP = 115.09
CYS = 103.15
GLN = 128.14
GLU = 129.12
GLY =  57.05
HIS = 137.14
ILE = 113.16
LEU = 113.16
LYS = 128.17
MET = 131.19
PHE = 147.18
PRO =  97.12
SER =  87.08
THR = 101.11
TRP = 186.21
TYR = 163.18
VAL =  99.14

[stokes_radius]
ALA = 3.8
ARG = 3.8
ASN = 3.8
ASP = 3.8
CYS = 3.8
GLN = 3.8
GLU = 3.8
GLY = 3.8
HIS = 3.8
ILE = 3.8
LEU = 3.8
LYS = 3.8
MET = 3.8
PHE = 3.8
PRO = 3.8
SER = 3.8
THR = 3.8
TRP = 3.8
TYR = 3.8
VAL = 3.8

[physical_constants]
# 1 Energy [kcal/mol] = 6.9478e-21 [kg  m^2/s^2] (= [J])
#                     = 6.9478e-1  [kg  Å^2/s^2] (1e+10[Å] = 1[m])
#                     = 4.1842e+26 [amu Å^2/s^2] (1 / 1.6605e-27[amu] = 1 [kg])
# 1 Time := 1.0 / sqrt(4.1842e+26) [s] = 4.8887e-14 ~ 49 [fs]
"τ"  = 4.8887e-14 # timestep               [s]
e    = 1.6021e-19 # elementaly charge      [C]
kB   = 1.9871e-3  # Boltzmann constant     [kcal/mol/K]
NA   = 6.0221e+23 # Avogadro's number      [/mol]
"ε0" = 2.3964e-4  # permittivity of vacuum [e^2/((kcal/mol)Å)]
"μ"  = 2.3553     # viscosity of water     [amu/(Å.τ)]
