[mass]
H =  1.0080
P = 30.9738
O = 15.9994
C = 12.0107
N = 14.0067

ALA =  71.09
ARG = 156.19
ASN = 114.11
ASP = 115.09
CYS = 103.15
GLN = 128.14
GLU = 129.12
GLY =  57.05
HIS = 137.14
ILE = 113.16
LEU = 113.16
LYS = 128.17
MET = 131.19
PHE = 147.18
PRO =  97.12
SER =  87.08
THR = 101.11
TRP = 186.21
TYR = 163.18
VAL =  99.14

[physical_constants]
kB = 1.986231313e-3
NA = 6.0221417930e23
e  = 1.60217648740e-19
"Îµ0" = 8.854187817e-12
